name: ci

on:
  push:               # Triggers the workflow on new tags
    tags:
      - '**'
  workflow_dispatch:  # Allows you to run this workflow manually from the Actions tab

jobs:
  build-dotfiles-image:
    runs-on: ubuntu-latest         # The type of runner that the job will run on

    steps:                         # Steps represent a sequence of tasks that will be executed as part of the job
      - uses: actions/checkout@v3  # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Get Current Timestamp
        id: timestamp
        run: echo "::set-output name=timestamp::$(date +'%Y-%m-%dT%H:%M:%S_%z')"

      - name: Build Docker image
        run: bash ./deployment/docker_build_ci.sh
        env:
          BUILD_VERSION: ${{ github.ref_name }}
          BUILD_DATE: ${{ steps.timestamp.outputs.timestamp }}
          VCS_REF: ${{ github.sha }}
          DOCKER_TAG: ${{ github.ref_name }}
