name: ci

on:
  push:               # Triggers the workflow on new tags
    tags:
      - '**'
  workflow_dispatch:  # Allows you to run this workflow manually from the Actions tab

jobs:
  build-dotfiles-image:
    runs-on: ubuntu-latest         # The type of runner that the job will run on

    steps:                         # Steps represent a sequence of tasks that will be executed as part of the job
      - uses: actions/checkout@v3  # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image
        run: zsh ./deployment/docker_build_ci.zsh
        env:
          BUILD_VERSION: "$GITHUB_REF_NAME"
          BUILD_DATE: "$(date +'%Y-%m-%d_T%H-%M-%S_%z')"
          VCS_REF: "$GITHUB_SHA"
          DOCKER_TAG: "$GITHUB_REF_NAME"
