name: Build CI

on:
  push:               # Triggers the workflow on new tags
    tags:
      - '**'

  workflow_dispatch:  # Allows you to run this workflow manually from the Actions tab
    inputs:
      build_ver:
        description: 'Build version'
        required: true
        default: 'manual'

jobs:
  build-dotfiles-image:
    runs-on: ubuntu-latest         # The type of runner that the job will run on

    steps:                         # Steps represent a sequence of tasks that will be executed as part of the job
      - uses: actions/checkout@v4  # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set Environment Variables
        id: set_env
        run: |
          # timestamp
          echo "timestamp=$(date +'%Y-%m-%dT%H:%M:%S_%z')" >> $GITHUB_OUTPUT

          # build_ver
          if [[ "${{inputs.build_ver}}" == '' ]]; then
              build_ver=${{github.ref_name}};
          else
              build_ver=${{inputs.build_ver}};
          fi
          echo "build_ver=$build_ver" >> $GITHUB_OUTPUT

      - name: Print Debug Info
        run: |
          echo ${{ steps.set_env.outputs.timestamp }}
          echo ${{ steps.set_env.outputs.build_ver }}

      - name: Build Docker image
        run: bash ./deployment/docker_build_ci.sh
        env:
          BUILD_VERSION: ${{ steps.set_env.outputs.build_ver }}
          BUILD_DATE: ${{ steps.timestamp.outputs.timestamp }}
          VCS_REF: ${{ github.sha }}
          DOCKER_TAG: ${{ steps.set_env.outputs.build_ver }}
